services:
  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pespatronpespatronvintrymaietseyraion

  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django_app
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pespatronpespatronvintrymaietseyraion
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
