services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pespatronpespatronvintrymaietseyraion
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"

  web:
    build: .
    image: musicroulette.azurecr.io/musicroulette
    container_name: musicroulette
    ports:
      - "80:80"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pespatronpespatronvintrymaietseyraion
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
